In [ ]:
'''assignment no. 6
    Title of the Assignment: Data Analytics III 
    1. Implement simple Naive Bayes classification algorithm using Python/R on iris.csv dataset. 
    2. Compute confusion matrix to find TP, FP, TN, FN, Accuracy, Error rate, Precision, Recall 
    on the given dataset.'''

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

dataset=pd.read_csv('iris.csv')
X=dataset.iloc[:,:4].values 
y = dataset['Species'].values
print(dataset.head(5)) 

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa


In [2]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
from sklearn import preprocessing
sc = preprocessing.StandardScaler()
X_train = sc.fit_transform(X_train) 
X_test = sc.transform(X_test)

In [4]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB() 
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test) 
y_pred

array(['Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica'], dtype='<U15')

In [5]:
# Confusion Matrix and Accuracy 
from sklearn.metrics import confusion_matrix 
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import accuracy_score
print("Accuracy : ", accuracy_score(y_test, y_pred)) 
print(cm)

Accuracy :  1.0
[[12  0  0]
 [ 0  8  0]
 [ 0  0 10]]


In [6]:
# Comparing the Real Values with Predicted Values
df = pd.DataFrame({'Real Values':y_test, 'Predicted Values':y_pred})
print(df)

        Real Values Predicted Values
0   Iris-versicolor  Iris-versicolor
1    Iris-virginica   Iris-virginica
2    Iris-virginica   Iris-virginica
3   Iris-versicolor  Iris-versicolor
4    Iris-virginica   Iris-virginica
5   Iris-versicolor  Iris-versicolor
6       Iris-setosa      Iris-setosa
7       Iris-setosa      Iris-setosa
8    Iris-virginica   Iris-virginica
9       Iris-setosa      Iris-setosa
10      Iris-setosa      Iris-setosa
11      Iris-setosa      Iris-setosa
12  Iris-versicolor  Iris-versicolor
13   Iris-virginica   Iris-virginica
14      Iris-setosa      Iris-setosa
15  Iris-versicolor  Iris-versicolor
16      Iris-setosa      Iris-setosa
17  Iris-versicolor  Iris-versicolor
18   Iris-virginica   Iris-virginica
19   Iris-virginica   Iris-virginica
20      Iris-setosa      Iris-setosa
21  Iris-versicolor  Iris-versicolor
22   Iris-virginica   Iris-virginica
23   Iris-virginica   Iris-virginica
24      Iris-setosa      Iris-setosa
25      Iris-setosa      Iris-setosa
2

In [9]:
#We have to import precision_score, recall_score, accuracy_score from sklearn.metrics 
from sklearn.metrics import precision_score, recall_score, accuracy_score
m=accuracy_score(y_test, y_pred) 
print("error rate:-",1-m) 

error rate:- 0.0


In [10]:
print('Precision:',precision_score(y_test,y_pred,average='micro'))

Precision: 1.0


In [11]:
print("Recall Score:",recall_score(y_test,y_pred,average='micro'))

Recall Score: 1.0


In [ ]:
'''Thus, in this way we have successfully been able to build a Naive Bayes Classification Model 
that is able to classify a flower depending upon 4 characteristic features. This model can be 
implemented and tested with several other classification datasets that are available on the net.'''